-- Skill catalog and practical challenge bank
INSERT INTO skills (name, category, aliases) VALUES
    ('Java', 'Language', 'java8,java11,java17,core java'),
    ('Spring Boot', 'Framework', 'spring,springboot'),
    ('PostgreSQL', 'Database', 'postgres,psql'),
    ('SQL', 'Database', 'sql queries'),
    ('Docker', 'DevOps', 'container,dockerfile'),
    ('Kubernetes', 'DevOps', 'k8s,kubectl'),
    ('AWS', 'Cloud', 'amazon web services'),
    ('Kafka', 'Data', 'apache kafka,messaging'),
    ('React', 'Frontend', 'reactjs,react.js'),
    ('TypeScript', 'Language', 'ts'),
    ('JavaScript', 'Language', 'js,es6'),
    ('Node.js', 'Runtime', 'node,nodejs,express'),
    ('Python', 'Language', 'py'),
    ('Go', 'Language', 'golang'),
    ('System Design', 'Architecture', 'system architecture,hld'),
    ('DSA', 'Fundamentals', 'data structures,algorithms'),
    ('REST API', 'Architecture', 'rest,restful,api design'),
    ('Redis', 'Database', 'caching'),
    ('GraphQL', 'API', 'apollo'),
    ('Terraform', 'DevOps', 'iac')
ON CONFLICT (name) DO NOTHING;

INSERT INTO practical_challenges (slug, title, skill_name, type, difficulty, prompt, rubric, required_keywords, est_minutes) VALUES
    ('lru-cache', 'Implement an LRU Cache', 'Java', 'CODING', 'MEDIUM',
     'Design and implement an LRU cache with O(1) get and put operations. Describe your data structures, walk through get/put flows, and explain eviction.',
     'Uses hashmap + doubly linked list or LinkedHashMap; explains O(1) ops; handles capacity; discusses thread-safety options.',
     'hash map|hashmap|linkedhashmap, doubly linked list|linked list, O(1)|constant time, evict|capacity', 30),
    ('rest-validation-endpoint', 'REST endpoint with validation & pagination', 'Spring Boot', 'REST_API', 'MEDIUM',
     'Create a REST endpoint with bean validation, global exception handling, and pagination. Describe controller, DTOs, exception advice, and repository paging.',
     'Bean Validation annotations; @RestControllerAdvice; Pageable/PageRequest; consistent error response; correct HTTP codes.',
     'valid|@Valid|jakarta validation, advice|exceptionhandler|controlleradvice, pageable|page request|page, status code|httpstatus|responseentity', 40),
    ('top-customers-sql', 'Top 3 customers by order value', 'SQL', 'SQL', 'EASY',
     'Given customers(id,name) and orders(id,customer_id,total), write a query for the top 3 customers by total order value. Explain your join and grouping.',
     'Correct aggregation with SUM + GROUP BY; ordering DESC; LIMIT 3; sensible join.',
     'sum(|group by, order by, limit 3|fetch first|top 3, join', 15),
    ('dockerize-app', 'Containerize this Spring Boot application', 'Docker', 'CONCEPT', 'MEDIUM',
     'Write a production-sane Dockerfile for a Spring Boot jar and describe how you would run it with Postgres via docker compose. Cover layers, JVM flags, health checks.',
     'Multi-stage build; non-root user; proper base image; compose service wiring; env config for DB URL; healthcheck mention.',
     'from openjdk|from eclipse-temurin|from amazoncorretto|multi-stage, copy|jar|layers, compose|docker-compose, healthcheck|non-root|jvm flags', 25),
    ('idempotent-payments', 'Design an idempotent payment endpoint', 'REST API', 'SYSTEM_DESIGN', 'HARD',
     'Design an idempotent payment creation endpoint. Cover idempotency keys, retries, storage of results, race conditions, and response replay semantics.',
     'Idempotency-Key header; unique constraint on key; store first result; replay stored response; discuss races/timeouts.',
     'idempotency key|idempotency-key, retry, store|persist|unique constraint|database, replay|same response|race', 35),
    ('url-shortener', 'Design a URL shortener for millions of requests', 'System Design', 'SYSTEM_DESIGN', 'HARD',
     'Design a URL shortener handling millions of requests/day. Cover ID generation, storage choice, redirect path, caching, analytics, and rate limiting.',
     'Base62/counter ID strategy; KV/document storage; cache hot links (Redis); read-heavy reasoning; async click analytics; rate limits.',
     'base62|counter|id generation, redis|cache|cdn, database|key-value|dynamodb|store, analytics|async, rate limit', 45),
    ('kafka-producer-consumer', 'Build a Kafka producer-consumer demo', 'Kafka', 'ARCHITECTURE', 'MEDIUM',
     'Describe building a Kafka producer/consumer demo in Java: topic setup, serialization, consumer group behavior, offset commits, and failure handling.',
     'Producer config with serializers; consumer group + partition assignment; commit strategies (auto vs manual); rebalance awareness; error/retry path.',
     'topic, serializer|serde|stringserializer|json, group id|consumer group|partition, offset|commit, rebalance|retry|error handling', 40)
ON CONFLICT (slug) DO NOTHING;
